djangoassessment/assessment/assessment/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gradebook/', include('gradebook.urls'))
]

djangoassessment/assessment/gradebook/urls.py
from django.urls import path
from .views import get_student_details, get_grades, add_score

app_name = 'gradebook'

urlpatterns = [
    path('student/<int:student_id>', get_student_details, name='student_details'),
    path('student/<int:student_id>/grades', get_grades, name='grades'),
    path('student/<int:student_id>/grades/add', add_score, name='add_score')
]

djangoassessment/assessment/gradebook/models.py
from django.db import models

'''
Each Student has multiple subjects each of which has a corresponding score.
This has been modelled using a Student table and a Subject table that has a foreign key
relationship to the Student table's primary key (id).
This means each Student object has a subject_set which is a set of Subject objects that contain scores.
'''

class Student (models.Model):
    name = models.CharField(max_length=256)
    roll_number = models.IntegerField(null=False)
    institution = models.CharField(max_length = 256)

class Subject (models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject_name = models.CharField(max_length=100)
    score = models.IntegerField(null=False)

djangoassessment/assessment/gradebook/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Student, Subject
def get_student_details(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    return render(request, 'gradebook/student_details.html', {'student': student})

def get_grades(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    #your code here
    return render(request, 'gradebook/grades.html', {'student': student})

def add_score(request, student_id):
    #your code here
    return HttpResponse("I don't do anything yet")

djangoassessment/assessment/gradebook/templates/gradebook/grades.html
<style>
    table, th, td {
      border:1px solid black;
    }
</style>

<h1>{{ student.institution }}</h1>
<h3>{{ student.roll_number }} - {{ student.name }}</h3>

<table>
    <form action="{% url 'gradebook:add_score' student.id %}" method="POST">
    {% csrf_token %}
        <tr>
            <th>Subject</th>
            <th>Score</th>
        </tr>
        <tr>
            <td>subject goes here</td>
            <td>Marks go here</td>
        </tr>
        <tr>
            <td>subject goes here</td>
            <td>Marks go here</td>
        </tr>
        <tr>
            <td>subject goes here</td>
            <td>Marks go here</td>
        </tr>
        <tr>
            <td>subject goes here</td>
            <td>Marks go here</td>
        </tr>
        <tr>
            <td>Total</td>
            <td>Total marks go here</td>
        </tr>
        <tr>
            <td>Grade</td>
            <td>Compute grade and print here</td>
        </tr>
        <tr>
            
                    <td>
                        <input type="text" name="subject" id="subject">
                    </td>
                    <td>
                        <input type="text" name="marks" id="marks">
                    </td>
                    <td>
                        <input type="submit" value="Add mark!">
                    </td>        
        </tr>
    </form>
</table>

djangoassessment/assessment/gradebook/templates/gradebook/student_details.html
<h1>{{ student.institution }}</h1>
<h3>{{ student.roll_number }} - {{ student.name }}</h3>
<button type="button"> <a href="{% url 'gradebook:grades' student.id%}">Grades</a> </button>