djangoproject/first_app/blog/urls.py
from django.urls import path
from .views import index, post_20221101

urlpatterns = [
    path('', index, name = 'index'),
    path('20221101', post_20221101, name = '20221101')
]

djangoproject/first_app/first_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index),
    path('', index),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('poll/', include('poll.urls'))
]

djangoproject/first_app/poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'
urlpatterns = [
    path('', views.index),
    path('<int:question_id>/', views.detail, name = 'detail'),
    path('<int:question_id>/results/', views.results, name = 'results'),
    path('<int:question_id>/vote/', views.vote, name = 'vote')
]

djangoproject/first_app/shop/urls.py
from django.urls import path, include
from .views import index, allemployees,employee_detail, AttendancePageView, giveattendance, NonsenseView, addnonsense, show_restricted_page, toggle_access

app_name='shop'

urlpatterns = [
    path('', index, name = 'index'),
    path('employees/all', allemployees, name = 'allemployees'),
    path('employee/<int:employee_id>', employee_detail, name = 'employee_detail'),
    path('employee/<int:pk>/attendance', AttendancePageView.as_view(), name='show_attendance_page'),
    path('employee/<int:employee_id>/attendance/give_attendance', giveattendance, name='give_attendance'),
    path('nonsense/', NonsenseView.as_view(), name='display_nonsense'),
    path('nonsense/add', addnonsense, name='add_nonsense'),
    path('restricted', show_restricted_page, name='show_restricted_page'),
    path('restricted/toggle', toggle_access, name='toggle_access')
]

djangoproject/first_app/blog/models.py
from django.db import models

# Create your models here.

djangoproject/first_app/poll/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published', auto_now = True)

    def __str__(self):
        return f'id: {self.id} question: {self.question_text}'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 50)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text

djangoproject/first_app/shop/models.py
from django.db import models

'''
As long as there is a definition for a class here,
Django will automatically create the SQL required for creating the table
It automatically adds an id column unless specifically configured to not add it
It creates other columns based on variable declarations within the class.
AS LONG AS YOUR MODEL CLASS IS A SUBCLASS OF models.Model
FRAMEWORKS HAVE OPINIONATED DEFAULTS
'''

class Employee (models.Model):
    name = models.CharField(max_length = 256)
    salary = models.IntegerField(default = 0)

    def __repr__(self):
        return f'{self.name} draws salary {self.salary}'
    
    def __str__(self):
        return f'{self.name} draws salary {self.salary}'
    
class Attendance (models.Model):
    employee = models.ForeignKey(Employee, on_delete = models.CASCADE)
    date = models.DateTimeField('date')
    is_present = models.BooleanField()

    def __str__(self):
        present = {True: "present", False: "absent"}[self.is_present]
        return f'{self.employee.name} was {present} on {self.date}'

class Nonsense (models.Model):
    message = models.TextField()

    def __str__(self):
        return f'{self.message}'

djangoproject/first_app/blog/views.py
from django.shortcuts import render

from django.http import HttpResponse

def index(request):
    return render(request, 'blog/home.html')

def post_20221101(request):
    return HttpResponse('Today is the 1st of November')

djangoproject/first_app/first_app/views.py
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello world")

djangoproject/first_app/poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice

def detail(request, question_id):
    try:
        question = Question.objects.get(pk = question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'poll/detail.html', {'question': question})

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'poll/results.html', {'question': question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        form_choice = request.POST['choice']
        selected_choice = question.choice_set.get(pk = form_choice)  # type: ignore
    except KeyError:
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    except Choice.DoesNotExist:
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "The form has sent a response that isn't a choice for this question",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('poll:results', args = (question.id,))) #type: ignore

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'poll/index.html', context)

djangoproject/first_app/shop/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
import requests

from .models import Employee, Attendance, Nonsense

def index(request):
    return render(request, 'shop/home.html')

def allemployees(request):
    context = {'all_employees': Employee.objects.all()}
    return render(request, 'shop/allemployees.html', context)

def employee_detail(request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)
    attendance_records = employee.attendance_set.all().order_by('date')
    return render(request, 'shop/employee_detail.html', {'employee': employee, 'attendance_records': attendance_records})

class AttendancePageView (generic.DetailView):
    model = Employee
    template_name = 'shop/employee_attendance.html'


def show_attendance_page (request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)
    return render(request, 'shop/employee_attendance.html', {'employee': employee})

def giveattendance(request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)
    date = request.POST['attendance_date']
    is_present = request.POST['attendance'] == 'present'
    attendance = Attendance(employee=employee,date=date,is_present=is_present)
    attendance.save()
    return HttpResponseRedirect(reverse('shop:employee_detail', args=(employee_id,)))

class NonsenseView (generic.ListView):
    template_name = 'shop/message_book.html'
    #context_object_name = 'nonsenses'

    def get_queryset(self):
        return Nonsense.objects.all()

def show_restricted_page(request):
    #request.session['allowed_access'] might raise a KeyError
    user_name = request.session.get('name', 'aruvi')
    response = requests.get(f'http://api.agify.io/?name={user_name}')
    if response.status_code != 200:
        raise ValueError('some issue in fetching agify data')
    agify_data = response.json()
    print(agify_data['age'])
    allowed_access = agify_data['age'] != None and agify_data['age'] > 21
    return render(request, 'shop/restricted.html', {'allowed_access': allowed_access})

def toggle_access(request):
    request.session['name'] = request.POST['name']
    return HttpResponseRedirect(reverse('shop:show_restricted_page'))

def addnonsense(request):
    new_message = request.POST['newmessage']
    n = Nonsense(message=new_message)
    n.save()
    return HttpResponseRedirect(reverse('shop:display_nonsense'))

djangoproject/first_app/blog/templates/blog/home.html
<!doctype html>
    <html>
        <head>
            <title>Loonycorn!</title>
        </head>
        <body>
            Welcome to D-jango
            <img src="../static/blog/Game.png"/>
            <p>If you want to statically load something into your django template</p>
            <p>(Something could be an image, some CSS, some javascript)</p>
            <p>Put it in [appname]/static/[appname]/[foldername]</p>
            <p>And refer to it using src or href with the location "../static/[appname]/[foldername]</p>
        </body>
    </html>

djangoproject/first_app/poll/templates/poll/detail.html
<form action="{% url 'poll:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}
        {%for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="vote">
</form>

djangoproject/first_app/poll/templates/poll/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'poll:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

djangoproject/first_app/poll/templates/poll/results.html
{% if question %}
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poll:detail' question.id %}">Vote again?</a>
{% endif %}

djangoproject/first_app/shop/templates/shop/allemployees.html
{% if all_employees %}
    <ul>
        {% for employee in all_employees %}
            <li>{{employee}}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No employees</p>
{% endif %}

djangoproject/first_app/shop/templates/shop/employee_attendance.html
<form action="{% url 'shop:give_attendance' employee.id %}" method="post">
    {% csrf_token %}
    <p>For {{employee.name}}:</p>
    <label for="attendance_date">Date: </label>
    <input type="date" id="attendance_date" name="attendance_date">
    <label for="present">Present</label>
    <input type="radio" id="present" name="attendance" value="present">
    <label for="absent">Absent</label>
    <input type="radio" id="absent" name="attendance" value="absent">
    <input type="submit" value="vote">
</form>

djangoproject/first_app/shop/templates/shop/employee_detail.html
{% if employee %}
<p>Employee id {{employee.id}} has the name {{employee.name}} and draws {{employee.salary}}</p>
<ul>
{% for attendance_item in attendance_records %}
    <li>{{attendance_item}}</li>
{% endfor %}
</ul>
<a href="{% url 'shop:show_attendance_page' employee.id %}">Give attendance</a>
{% endif %}

djangoproject/first_app/shop/templates/shop/home.html
<!doctype html>
    <html>
        <head>
            <title>Loonycorn!</title>
        </head>
        <body>
            Welcome to D-jango
            <img src="../static/shop/images/Game.png"/>
            <p>If you want to statically load something into your django template</p>
            <p>(Something could be an image, some CSS, some javascript)</p>
            <p>Put it in [appname]/static/[appname]/[foldername]</p>
            <p>And refer to it using src or href with the location "../static/[appname]/[foldername]</p>
        </body>
    </html>

djangoproject/first_app/shop/templates/shop/message_book.html
{% for nonsense in nonsense_list %}
<p>{{ nonsense.id }} {{nonsense.message}}</p>
{% endfor %}
<form action="{% url 'shop:add_nonsense' %}" method="POST">
    {% csrf_token %}
    <label for="newmessage">Write some Nonsense here</label>
    <input type="text" name="newmessage" id="newmessage">
    <input type="submit">
</form>

djangoproject/first_app/shop/templates/shop/restricted.html
{% if allowed_access == True %}
<p>Top secret content</p>
{% else %}
<p>Restricted!</p>
{% endif %}
<form action="{% url 'shop:toggle_access' %}" method="POST">
    {% csrf_token %}
    <label id="name">Name</label>
    <input type="text" id="name" name="name">
    <button type="submit">Does agify think I'm old enough?</button>
</form>